{{- if not .Values.nodeComponentOnly -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ebs-csi-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aws-ebs-csi-driver.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: ebs-csi-controller
      {{- include "aws-ebs-csi-driver.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Egress
  egress:
  - {}
{{- end }}
