apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ebs-csi-node
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aws-ebs-csi-driver.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: ebs-csi-node
      {{- include "aws-ebs-csi-driver.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Egress
  egress:
  - {}
