{{- if and .Values.controller.serviceAccount.create (not .Values.nodeComponentOnly) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.controller.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aws-ebs-csi-driver.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.clusterID }}-ebs-csi-driver-role
  {{- with .Values.controller.serviceAccount.annotations }}
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
{{- if .Values.controller.serviceAccount.automountServiceAccountToken }}
automountServiceAccountToken: {{ .Values.controller.serviceAccount.automountServiceAccountToken }}
{{- end }}
{{- end -}}
